Repository AY2425S1-CS2103T-F14b-1/tp, pull requests merged in 2024-11, with the labels that each got.

#136 Add tests for ListAppointmentCommand
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.Task

#120 Change DateOfBirth value to be LocalDate instead of String
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/scheme/SchemeRetrieval.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/DateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#124 Shorten family size prefix and add support for editing family size of person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#125 Add support for archiving persons in the address book
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ArchiveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#144 Make previous command operation fail silently
  src/main/java/seedu/address/logic/CommandHistory.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
Labels: severity.Low, alpha-bug

#147 Fix date of birth formatting in AddCommand's message usage
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, severity.High

#132 Add support for editing appointments
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/util/ToStringBuilder.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GetCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SchemeCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/CalendarViewPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Story, priority.Medium

#150 Add sort command to help for user
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/testutil/TypicalPastCommands.java
Labels: severity.Low, alpha-bug

#158 Change sample persons
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, severity.Low

#161 Improve phrasing on messages in archive and unarchive commands
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
Labels: type.Task, severity.VeryLow

#159 Update user guide for edit, list, archive and unarchive commands
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#151 Add new sorting parameter: Last updated
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#175 Change how list is shown after executing add and edit
  src/main/java/seedu/address/logic/commands/AddSchemeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSchemeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, severity.High, alpha-bug

#167 Update UG - sort and find
  docs/UserGuide.md
  docs/images/findResult.png
  docs/images/newFindAlexDavidResult.png
Labels: alpha-bug

#164 Update help window to support new commands
  src/main/java/seedu/address/logic/commands/AddSchemeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSchemeCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#180 Update undo after clearing all data
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#181 Add info about using up and down to go through commands
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#185 Add exit command to command summary
  docs/UserGuide.md
Labels: alpha-bug

#183 Edit landing page of SocialBook
  docs/images/latestUI.png
  docs/index.md
Labels: type.Enhancement, priority.High

#186 Update images in UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findResult.png
  docs/images/helpMessage.png
  docs/images/latestUI.png
  docs/images/updatedHelpMessage.png
  docs/index.md
  src/main/java/seedu/address/model/person/Phone.java
Labels: priority.High

#257 Add tests for deleting appointments
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#256 Fix income rounding bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Income.java
Labels: type.Bug, severity.High

#258 Fix PE-D bugs
  docs/UserGuide.md
  docs/images/sortResult.png
Labels: type.Bug, priority.High

#254 Fix PE-D bugs
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSchemeCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSchemeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#252 Fix PE-D bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GetCommandParser.java
  src/test/java/seedu/address/logic/commands/StatisticsCommandTest.java
Labels: severity.High

#261 Give examples for user input - UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#259 Fix list command non-empty preamble bug and improve code quality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium

#260 Fix invalid add command examples and edit list command description in user guide
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#253 Fix PE-D bugs
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/parser/AddSchemeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSchemeCommandParser.java
Labels: severity.High

#264 Update UG with more screenshots
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addAppointment.png
  docs/images/calendarView.png
  docs/images/calendarWithAgendaView.png
  docs/images/calendarWithoutAgendaView.png
  docs/images/findResult.png
  docs/images/listArchive.png
  docs/images/newHelpMessage.png
  docs/images/sampleData.png
  docs/images/sortResult.png
Labels: priority.High

#262 Add tests for adding appointments
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
Labels: type.Task

#266 Add page breaks to UG
  docs/UserGuide.md
  docs/images/addAppointment.png
Labels: priority.High

#255 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#162 Update data archiving section in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/style.puml
Labels: priority.Medium

#268 Update UML diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High

#265 Include planned enhancements in DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/CommandHistory.java
Labels: type.Enhancement, priority.High

#270 Add changes to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/model/person/predicates/IncomePredicate.java
  src/main/java/seedu/address/model/person/predicates/PriorityPredicate.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement, priority.Medium

#271 Add page breaks to DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: priority.High
